### ISSUE TITLE
Autocomplete working?

### ISSUE THREAD

**Issue by BetaKevin** [jpbarto/atom-cform-yaml#1]
I tried this package out in my setup and the autocomplete snippets aren't showing.  I believe I'm affected by https://github.com/atom/autocomplete-snippets/issues/55.  Do you know how you got your autocomplete working?

stack-start works but nothing after that because it looks like most things fall into string which autocomplete doesn't seem to support (currently).

https://github.com/jpbarto/atom-cform-yaml/blob/master/build.sh#L5
I think you meant to do 
```mv snippets.generated snippets```

**Comment by jpbarto** [comment]
BetaKevin - thanks for downloading the package!

Please see the pull request I submitted to the project to correct the issue you're encountering: https://github.com/atom/autocomplete-snippets/pull/77

Also please pull a patched version of the package, 0.3.2, to have the snippets built and in the right place.  Didn't realize the version from GitHub was published via APM rather than the local 'built' copy of the working dir.

**Comment by BetaKevin** [comment]
Thanks for the tips.  That fixed it.  Hopefully they will merge that fix in soon and release it.  Its been hanging out there for a while.

I put together nearly the same thing as this over this last weekend (before I found this project).  I ended up creating my own atom grammar which was just a spin off of the yaml grammar but "fixed" the string issues.  With that new grammar I was able to put together more exact location for autocomplete.  (.parameters.cloudformation inside source.cloudformation as an example).  Which let me really limit the snippets.  Thanks for the good work.

**Comment by jpbarto** [comment]
Kevin,

That sounds interesting and would help to make the snippets much smarter.
Could you share the project and work you've done? Perhaps we could merge
the two so autocomplete doesn't suggest a stack output (for example) in the
resources section of the yaml document.

**Comment by BetaKevin** [comment]
Here is what I came up with.  https://github.com/BetaKevin/atom-cfm  Not very complete... so take from it what you can.
